# Generated by Django 5.1.1 on 2024-09-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dat',
            new_name='date',
        ),
    ]
