# Generated by Django 5.1.1 on 2024-09-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_dat_movie_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
